### ISSUE TITLE
Battlepoint Conquest Point System

### ISSUE THREAD

**Issue by HaedHutner** [Atherys-Horizons/AtherysBattlegrounds#46]
## Whenever a battlepoint is captured:
- The team which captured the point has x conquest points deposited into their team balance.
- Each player who helped capture the point has x amount of sickles deposited into their balance.
- Each player who helped capture the point also has x amount of conquest points deposited into their balance.

## For each interval a battlepoint remains within control of a team:
- The currently controlling team has x amount of conquest points deposited into their team balance.

## For killing a player of the opposite team inside a battle point:
- The killer has x amount of conquest points deposited into their balance.
- The killer's team has x amount of conquest points deposited into their team balance.

## For killing a player of the opposite team outside a battle point:
- The killer has x amount of conquest points deposited into their balance.
- The killer's team has x amount of conquest points deposited into their team balance.
- This will be much less than for killing a player inside a battle point.

**Comment by HaedHutner** [comment]
Related to #42 and #43 . Supersedes both.

**Comment by HaedHutner** [comment]
Example Configuration:
```
# what's displayed in the menu
milestones-title=""
# the conquest point currency id
milestone-currency=
# the milestones
milestones=[
  {
    # How many conquest points are required in order to get this milestone
    threshold=50
    # Message sent to the player once they achieve the milestone
    message=""
    # how the milestone is represented in the menu
    display=""
    # The reward for reaching this milestone
    award {
      currency {
        ""=500
      }
      commands=[
        "spawnitem sword {player}"
      ]
    }
  }
]
```

Also added were additional award configurations for kills in the main config under the alias `award-for-kills`

**Comment by fingoltin** [comment]
This was done a while ago, oops.
